### ISSUE TITLE
JMM Server Login Failed

### ISSUE THREAD

**Issue by ElementalCrisis** [japanesemediamanager/AnimeBuddy#5]
Hello,

Decided to check out AnimeBuddy but keep running into this problem when I try to link JMM Server up. 

JMM Server is set to localhost and JMM Server Port is 8111. I've copied the MySQL username and password directly from JMMServer.exe.Config yet every time I connect I get login failed even though the same exact information works in JMM Server.

**Comment by jmediamanager** [comment]
Hi, you should be entering the same username and password that you use for JMM Desktop
 e.g.

Username:   Default
Password:    <blank>

NOTE - I will probably stop work on Anime Buddy, as Plex is the better solution at the moment
